const GithubSlugger = require('github-slugger').default;
const headings = [
  'youtube-dl-gui',
  'Table of contents · Оглавление',
  'Quick command cheat sheet (Windows)',
  'Prerequisites',
  'First run (Windows)',
  'Build and run from this repo',
  'Desktop shortcut (optional)',
  'Prebuilt release',
  'Usage',
  'Quick downloader',
  'Extended downloader',
  'Project backup (Python)',
  'Custom Arguments',
  'Compatible sites',
  'Compiling',
  'Dependencies',
  'Linux',
  'Contributing',
  'What is that hyphen in the version number?',
  'youtube-dl-gui — русский',
  'Все команды — шпаргалка (Windows)',
  'Требования',
  'Первый запуск (Windows)',
  'Сборка и запуск из этого репозитория',
  'Ярлык на рабочем столе (по желанию)',
  'Готовая сборка (релиз)',
  'Использование',
  'Быстрая загрузка',
  'Расширенная загрузка',
  'Бекап проекта (Python)',
  'Произвольные аргументы',
  'Поддерживаемые сайты',
  'Сборка',
  'Зависимости',
  'Linux',
  'Участие в проекте',
  'Что значит дефис в номере версии?',
];
const slugger = new GithubSlugger();
headings.forEach((h, i) => {
  console.log(i + 1, JSON.stringify(h), '->', slugger.slug(h));
});
